<a href="https://colab.research.google.com/github/Sneha00724/CODSOFT/blob/main/Task2(CodSoft).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MOVIE RATING PREDICTION USING PYTHON

In [ ]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving IMDb Movies India.csv to IMDb Movies India.csv
User uploaded file "IMDb Movies India.csv" with length 1382851 bytes

In [ ]:
import pandas as pd
df = pd.read_csv("IMDb Movies India.csv", encoding='latin1')
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali

## Exploratory Data Analysis (EDA)

Let's begin by examining the basic information of the dataset, including column types and non-null values. This will help us identify potential data cleaning or preprocessing steps needed.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

In [ ]:
print(df.isnull().sum())

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

## Data Cleaning

In [ ]:
# Remove parentheses from 'Year' column and convert to numeric
df['Year'] = df['Year'].str.extract('(\d+)').astype(float)

# Display updated info and null values for 'Year'
df.info()
print(df['Year'].isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  float64
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(2), object(8)
memory usage: 1.2+ MB
528

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_825/1232480073.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['Year'] = df['Year'].str.extract('(\d+)').astype(float)

In [ ]:
# Fill missing 'Year' values with the median
median_year = df['Year'].median()
df['Year'].fillna(median_year, inplace=True)

# Convert 'Year' to integer type as years are whole numbers
df['Year'] = df['Year'].astype(int)

# Display updated info and null values for 'Year'
df.info()
print(df['Year'].isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15509 non-null  int64
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 1.2+ MB
0

/tmp/ipykernel_825/2927969854.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Year'].fillna(median_year, inplace=True)

In [ ]:
# Remove ' min' from 'Duration' column and convert to numeric
df['Duration'] = df['Duration'].str.replace(' min', '', regex=False).astype(float)

# Display updated info and null values for 'Duration'
df.info()
print(df['Duration'].isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15509 non-null  int64
 2   Duration  7240 non-null   float64
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 1.2+ MB
8269

In [ ]:
# Fill missing 'Duration' values with the median
median_duration = df['Duration'].median()
df['Duration'].fillna(median_duration, inplace=True)

# Display updated info and null values for 'Duration'
df.info()
print(df['Duration'].isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15509 non-null  int64
 2   Duration  15509 non-null  float64
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 1.2+ MB
0

/tmp/ipykernel_825/1605988526.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Duration'].fillna(median_duration, inplace=True)

In [ ]:
# Remove non-numeric characters (like '$', 'M') and commas from 'Votes' column and convert to numeric
df['Votes'] = df['Votes'].astype(str).str.replace(r'[$,M]', '', regex=True).str.replace(',', '', regex=False).astype(float)

# Fill missing 'Votes' values with the median
median_votes = df['Votes'].median()
df['Votes'].fillna(median_votes, inplace=True)

# Convert 'Votes' to integer type as votes are whole numbers
df['Votes'] = df['Votes'].astype(int)

# Display updated info and null values for 'Votes'
df.info()
print(df['Votes'].isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15509 non-null  int64
 2   Duration  15509 non-null  float64
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     15509 non-null  int64
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 1.2+ MB
0

/tmp/ipykernel_825/1160533372.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Votes'].fillna(median_votes, inplace=True)

In [ ]:
# Fill missing values in 'Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3' with 'Unknown'
for col in ['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3']:
    df[col].fillna('Unknown', inplace=True)

# Display updated info and null values for these columns
df.info()
for col in ['Genre', 'Director', 'Actor 1', 'Actor 2', 'Actor 3']:
    print(f"{col}: {df[col].isnull().sum()} null values")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      15509 non-null  int64
 2   Duration  15509 non-null  float64
 3   Genre     15509 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     15509 non-null  int64
 6   Director  15509 non-null  object
 7   Actor 1   15509 non-null  object
 8   Actor 2   15509 non-null  object
 9   Actor 3   15509 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 1.2+ MB
Genre: 0 null values
Director: 0 null values
Actor 1: 0 null values
Actor 2: 0 null values
Actor 3: 0 null values

/tmp/ipykernel_825/2108434186.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('Unknown', inplace=True)

In [ ]:
# Drop rows where 'Rating' is null
df.dropna(subset=['Rating'], inplace=True)

# Display updated info and null values for 'Rating'
df.info()
print(f"Rating: {df['Rating'].isnull().sum()} null values")

<class 'pandas.core.frame.DataFrame'>
Index: 7919 entries, 1 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      7919 non-null   object
 1   Year      7919 non-null   int64
 2   Duration  7919 non-null   float64
 3   Genre     7919 non-null   object
 4   Rating    7919 non-null   float64
 5   Votes     7919 non-null   int64
 6   Director  7919 non-null   object
 7   Actor 1   7919 non-null   object
 8   Actor 2   7919 non-null   object
 9   Actor 3   7919 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 680.5+ KB
Rating: 0 null values

## Feature Engineering

In [ ]:
# Split 'Genre' into multiple columns and apply One-Hot Encoding
expanded_genres = df['Genre'].str.get_dummies(sep=', ')
df = pd.concat([df, expanded_genres], axis=1)

# Drop the original 'Genre' column
df.drop('Genre', axis=1, inplace=True)

# Display the first few rows with new genre columns and info
print(df.head())
df.info()

                                 Name  Year  Duration  Rating  Votes  \
1  #Gadhvi (He thought he was Gandhi)  2019     109.0     7.0      8
3                             #Yaaram  2019     110.0     4.4     35
5                ...Aur Pyaar Ho Gaya  1997     147.0     4.7    827
6                           ...Yahaan  2005     142.0     7.4   1086
8                  ?: A Question Mark  2012      82.0     5.6    326

         Director          Actor 1                 Actor 2          Actor 3  \
1   Gaurav Bakshi     Rasika Dugal          Vivek Ghamande    Arvind Jangid
3      Ovais Khan          Prateik              Ishita Raj  Siddhant Kapoor
5    Rahul Rawail       Bobby Deol  Aishwarya Rai Bachchan    Shammi Kapoor
6  Shoojit Sircar  Jimmy Sheirgill          Minissha Lamba   Yashpal Sharma
8   Allyson Patel        Yash Dave          Muntazir Ahmad     Kiran Bhatia

   Action  ...  Musical  Mystery  News  Romance  Sci-Fi  Sport  Thriller  \
1       0  ...        0        0     0        0       0      0         0
3       0  ...        0        0     0        1       0      0         0
5       0  ...        1        0     0        0       0      0         0
6       0  ...        0        0     0        1       0      0         0
8       0  ...        0        1     0        0       0      0         1

   Unknown  War  Western
1        0    0        0
3        0    0        0
5        0    0        0
6        0    1        0
8        0    0        0

[5 rows x 32 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 7919 entries, 1 to 15508
Data columns (total 32 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         7919 non-null   object
 1   Year         7919 non-null   int64
 2   Duration     7919 non-null   float64
 3   Rating       7919 non-null   float64
 4   Votes        7919 non-null   int64
 5   Director     7919 non-null   object
 6   Actor 1      7919 non-null   object
 7   Actor 2      7919 non-null   object
 8   Actor 3      7919 non-null   object
 9   Action       7919 non-null   int64
 10  Adventure    7919 non-null   int64
 11  Animation    7919 non-null   int64
 12  Biography    7919 non-null   int64
 13  Comedy       7919 non-null   int64
 14  Crime        7919 non-null   int64
 15  Documentary  7919 non-null   int64
 16  Drama        7919 non-null   int64
 17  Family       7919 non-null   int64
 18  Fantasy      7919 non-null   int64
 19  History      7919 non-null   int64
 20  Horror       7919 non-null   int64
 21  Music        7919 non-null   int64
 22  Musical      7919 non-null   int64
 23  Mystery      7919 non-null   int64
 24  News         7919 non-null   int64
 25  Romance      7919 non-null   int64
 26  Sci-Fi       7919 non-null   int64
 27  Sport        7919 non-null   int64
 28  Thriller     7919 non-null   int64
 29  Unknown      7919 non-null   int64
 30  War          7919 non-null   int64
 31  Western      7919 non-null   int64
dtypes: float64(2), int64(25), object(5)
memory usage: 2.0+ MB

### Engineering 'Director' and 'Actor' Features

In [ ]:
# Count unique values for 'Director'
print(f"Number of unique Directors: {df['Director'].nunique()}")

# Count unique values for 'Actor 1', 'Actor 2', 'Actor 3'
print(f"Number of unique Actor 1: {df['Actor 1'].nunique()}")
print(f"Number of unique Actor 2: {df['Actor 2'].nunique()}")
print(f"Number of unique Actor 3: {df['Actor 3'].nunique()}")

In [ ]:
# Get the top 100 directors
top_directors = df['Director'].value_counts().head(100).index.tolist()

# Create binary columns for top directors
for director in top_directors:
    df[f'Director_{director}'] = df['Director'].apply(lambda x: 1 if director in x else 0)

print(f"Created {len(top_directors)} new director features.")

# Get all unique actors from Actor 1, Actor 2, Actor 3
all_actors = pd.concat([df['Actor 1'], df['Actor 2'], df['Actor 3']]).dropna().unique()

# Calculate frequency of each actor
actor_counts = pd.concat([df['Actor 1'], df['Actor 2'], df['Actor 3']]).value_counts()

# Get the top 100 actors
top_actors = actor_counts.head(100).index.tolist()

# Create binary columns for top actors
for actor in top_actors:
    df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)

print(f"Created {len(top_actors)} new actor features.")

/tmp/ipykernel_825/2462177331.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Director_{director}'] = df['Director'].apply(lambda x: 1 if director in x else 0)
/tmp/ipykernel_825/2462177331.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Director_{director}'] = df['Director'].apply(lambda x: 1 if director in x else 0)
/tmp/ipykernel_825/2462177331.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Director_{director}'] = df['Director'].apply(lambda x: 1 if director in x else 0)
/tmp/ipykernel_825/2462177331.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Director_{director}'] = df['Director'].apply(lambda x: 1 if director in x else 0)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)

Created 100 new director features.

/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)

Created 100 new actor features.

/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)
/tmp/ipykernel_825/2462177331.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'Actor_{actor}'] = df[['Actor 1', 'Actor 2', 'Actor 3']].apply(lambda x: 1 if actor in x.values else 0, axis=1)

In [ ]:
# Drop original categorical columns
df.drop(['Name', 'Director', 'Actor 1', 'Actor 2', 'Actor 3'], axis=1, inplace=True)

# Display the updated DataFrame info and head
df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 7919 entries, 1 to 15508
Columns: 227 entries, Year to Actor_Emraan Hashmi
dtypes: float64(2), int64(225)
memory usage: 13.8 MB

,Year,Duration,Rating,Votes,Action,Adventure,Animation,Biography,Comedy,Crime,...,Actor_Birbal,Actor_Poonam Dhillon,Actor_Nanda,Actor_Abhishek Bachchan,Actor_Priyanka Chopra Jonas,Actor_Kareena Kapoor,Actor_Saira Banu,Actor_Rakesh Roshan,Actor_Meenakshi Sheshadri,Actor_Emraan Hashmi
1,2019,109.0,7.0,8,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2019,110.0,4.4,35,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,1997,147.0,4.7,827,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,2005,142.0,7.4,1086,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,2012,82.0,5.6,326,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Model Preparation

In [ ]:
# Define features (X) and target (y)
X = df.drop('Rating', axis=1)
y = df['Rating']

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (6335, 226)
X_test shape: (1584, 226)
y_train shape: (6335,)
y_test shape: (1584,)

## Model Selection and Training

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Initialize the Random Forest Regressor model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
print("Training the RandomForestRegressor model...")
model.fit(X_train, y_train)
print("Model training complete.")

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"\nMean Squared Error (MSE): {mse:.4f}")
print(f"R-squared (R2): {r2:.4f}")

Training the RandomForestRegressor model...
Model training complete.

Mean Squared Error (MSE): 1.1792
R-squared (R2): 0.3657